version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - db
    command: gunicorn -c guni_app.py  application:application
    #command: /usr/local/lib/python3.9/site-packages/gunicorn --bind 0.0.0.0:5000 application:application
    environment:
      - FLASK_APP=${FLASK_APP:-application}
      - FLASK_ENV=${FLASK_ENV:-dev}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST:-0.0.0.0}
      - jwt_secret_key=${jwt_secret_key:-FAKE_JWT_SECRET_KEY}
      - secret_key=${secret_key:-FAKE_SECRET_KEY}
      - db_url=postgres://postgres:password@db:5432/dev
      - PYTHONUNBUFFERED=0
      - FLASK_DEBUG=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    #ports:
    #  - 5000:5000
    expose:
      - 5000
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  postgres_data:
